string = "kit_fox                                    \n \
English_setter                             \n \
Siberian_husky                             \n \
Australian_terrier                         \n \
English_springer                           \n \
grey_whale                                 \n \
lesser_panda                               \n \
Egyptian_cat                               \n \
ibex                                       \n \
Persian_cat                                \n \
cougar                                     \n \
gazelle                                    \n \
porcupine                                  \n \
sea_lion                                   \n \
malamute                                   \n \
badger                                     \n \
Great_Dane                                 \n \
Walker_hound                               \n \
Welsh_springer_spaniel                     \n \
whippet                                    \n \
Scottish_deerhound                         \n \
killer_whale                               \n \
mink                                       \n \
African_elephant                           \n \
Weimaraner                                 \n \
soft-coated_wheaten_terrier                \n \
Dandie_Dinmont                             \n \
red_wolf                                   \n \
Old_English_sheepdog                       \n \
jaguar                                     \n \
otterhound                                 \n \
bloodhound                                 \n \
Airedale                                   \n \
hyena                                      \n \
meerkat                                    \n \
giant_schnauzer                            \n \
titi                                       \n \
three-toed_sloth                           \n \
sorrel                                     \n \
black-footed_ferret                        \n \
dalmatian                                  \n \
black-and-tan_coonhound                    \n \
papillon                                   \n \
skunk                                      \n \
Staffordshire_bullterrier                  \n \
Mexican_hairless                           \n \
Bouvier_des_Flandres                       \n \
weasel                                     \n \
miniature_poodle                           \n \
Cardigan                                   \n \
malinois                                   \n \
bighorn                                    \n \
fox_squirrel                               \n \
colobus                                    \n \
tiger_cat                                  \n \
Lhasa                                      \n \
impala                                     \n \
coyote                                     \n \
Yorkshire_terrier                          \n \
Newfoundland                               \n \
brown_bear                                 \n \
red_fox                                    \n \
Norwegian_elkhound                         \n \
Rottweiler                                 \n \
hartebeest                                 \n \
Saluki                                     \n \
grey_fox                                   \n \
schipperke                                 \n \
Pekinese                                   \n \
Brabancon_griffon                          \n \
West_Highland_white_terrier                \n \
Sealyham_terrier                           \n \
guenon                                     \n \
mongoose                                   \n \
indri                                      \n \
tiger                                      \n \
Irish_wolfhound                            \n \
wild_boar                                  \n \
EntleBucher                                \n \
zebra                                      \n \
ram                                        \n \
French_bulldog                             \n \
orangutan                                  \n \
basenji                                    \n \
leopard                                    \n \
Bernese_mountain_dog                       \n \
Maltese_dog                                \n \
Norfolk_terrier                            \n \
toy_terrier                                \n \
vizsla                                     \n \
cairn                                      \n \
squirrel_monkey                            \n \
groenendael                                \n \
clumber                                    \n \
Siamese_cat                                \n \
chimpanzee                                 \n \
komondor                                   \n \
Afghan_hound                               \n \
Japanese_spaniel                           \n \
proboscis_monkey"

classes = string.split('\n')
print(classes)
for c in range(len(classes)):
    classes[c] = classes[c].strip()
print(classes)
